### ISSUE TITLE
No such file or directory Staging failed: Buildpack compilation step failed

### ISSUE THREAD

**Issue by bdm4** [ind1go/bluemix-buildpack-meteor#17]
This command:
cf push <your app name> -m 512M -b https://github.com/ind1go/bluemix-buildpack-meteor.git

Crashes like:
-----> Downloaded app package (3.4M)
-----> Downloaded app buildpack cache (456K)
    Cloning into '/tmp/buildpacks/bluemix-buildpack-meteor'...
    -----> Resolving engine versions
       No version of Node.js specified in nodeversion, using '0.10.*'
       Using Node.js version: 0.10.42
-----> Fetching Node.js binaries
        - downloading and extracting node from http://nodejs.org/dist/v0.10.42/n
ode-v0.10.42-linux-x64.tar.gz
       Installing meteor
######################################################################## 100.0%
Downloading Meteor distribution
######################################################################## 100.0%
Meteor 1.2.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.
sudo: no tty present and no askpass program specified
Couldn't write the launcher script. Please either:
  (1) Run the following as root:
        cp "/tmp/node-meteor-dSKG/.meteor/packages/meteor-tool/1.1.10/mt-os.linu
x.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
  (2) Add "$HOME/.meteor" to your path, or
  (3) Rerun this command to try again.
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
       Meteor installed
Ignoring build of mobile platforms
       Building meteor bundle
       rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm..
.
       rocketchat:assets: updating npm dependencies -- image-size, mime-types...

       rocketchat:cas: updating npm dependencies -- cas...
       rocketchat:ldap: updating npm dependencies -- ldapjs...
       builLivechat: updating npm dependencies -- shelljs...
       /tmp/staged/app/packages/rocketchat-livechat/plugin/build.sh: 1: cd: can'
t cd to packages/rocketchat-livechat/app
       /tmp/staged/app/packages/rocketchat-livechat/plugin/build.sh: 2: /tmp/sta
ged/app/packages/rocketchat-livechat/plugin/build.sh: meteor: not found
       /tmp/staged/app/packages/rocketchat-livechat/plugin/build.sh: 3: /tmp/sta
: not foundkages/rocketchat-livechat/plugin/build.sh:
       /tmp/staged/app/packages/rocketchat-livechat/plugin/build.sh: 5: /tmp/sta
: not foundkages/rocketchat-livechat/plugin/build.sh:
       /tmp/staged/app/packages/rocketchat-livechat/plugin/build.sh: 9: /tmp/sta
: not foundkages/rocketchat-livechat/plugin/build.sh:
       cp: cannot stat `.meteor/build/bundle/programs/web.browser/*.css': No suc
h file or directory
       cp: cannot stat `.meteor/build/bundle/programs/web.browser/*.js': No such
 file or directory
       cp: cannot stat `.meteor/build/bundle/programs/web.browser/head.html': No
 such file or directory
       /tmp/staged/app/packages/rocketchat-livechat/plugin/build.sh: 13: /tmp/st
: not foundckages/rocketchat-livechat/plugin/build.sh:
       /tmp/staged/app/packages/rocketchat-livechat/plugin/build.sh: 15: /tmp/st
: not foundckages/rocketchat-livechat/plugin/build.sh:
       /tmp/node-meteor-dSKG/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.lin
ux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules
/fibers/future.js:245
                                                throw(ex);
                                                      ^
       Error: Builder can not write without either data or a file path or a syml
ink path: os/packages/rocketchat_livechat/public/head.html
           at Builder.write (/tools/isobuild/builder.js:225:13)
           at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:353:1
0)
           at /tools/isobuild/isopack.js:1346:27
           at Array.forEach (native)
           at Function._.each._.forEach (/tmp/node-meteor-dSKG/.meteor/packages/
meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.
x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
           at _.each._.each.builder.generateFilename.directory (/tools/isobuild/
isopack.js:1320:11)
           at Array.forEach (native)
           at Function._.each._.forEach (/tmp/node-meteor-dSKG/.meteor/packages/
meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.
x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
           at /tools/isobuild/isopack.js:1233:9
           at [object Object]._.extend.saveToPath (/tools/isobuild/isopack.js:15
85:26)
           at /tools/isobuild/isopack-cache.js:289:23
           at /tools/utils/buildmessage.js:356:18
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:349:34
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:347:23
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at Object.enterJob (/tools/utils/buildmessage.js:321:26)
           at [object Object]._.extend._loadLocalPackage (/tools/isobuild/isopac
k-cache.js:227:18)
           at /tools/isobuild/isopack-cache.js:166:14
           at /tools/utils/buildmessage.js:356:18
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:349:34
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:347:23
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at Object.enterJob (/tools/utils/buildmessage.js:321:26)
           at [object Object]._.extend._ensurePackageLoaded (/tools/isobuild/iso
pack-cache.js:158:20)
           at /tools/isobuild/isopack-cache.js:73:14
           at /tools/packaging/package-map.js:57:7
           at Function._.each._.forEach (/tmp/node-meteor-dSKG/.meteor/packages/
meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.
x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
           at [object Object]._.extend.eachPackage (/tools/packaging/package-map
.js:49:7)
           at [object Object]._.extend.buildLocalPackages (/tools/isobuild/isopa
ck-cache.js:72:24)
           at /tools/project-context.js:735:25
           at /tools/utils/buildmessage.js:356:18
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:349:34
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:347:23
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at Object.enterJob (/tools/utils/buildmessage.js:321:26)
           at ProjectContext._.extend._buildLocalPackages (/tools/project-contex
t.js:734:18)
           at /tools/project-context.js:257:35
           at /tools/utils/buildmessage.js:356:18
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:349:34
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:347:23
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at Object.enterJob (/tools/utils/buildmessage.js:321:26)
           at ProjectContext._.extend._completeStagesThrough (/tools/project-con
text.js:247:18)
           at ProjectContext._.extend.saveChangedMetadata (/tools/project-contex
t.js:235:10)
           at ProjectContext._.extend.prepareProjectForBuild (/tools/project-con
text.js:240:10)
           at /tools/cli/commands.js:838:20
           at /tools/utils/buildmessage.js:268:13
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:261:29
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:259:18
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at /tools/utils/buildmessage.js:250:23
           at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:
114:14)
           at Object.capture (/tools/utils/buildmessage.js:249:19)
           at Object.main.captureAndExit (/tools/cli/main.js:270:29)
           at buildCommand (/tools/cli/commands.js:837:8)
           at Command.main.registerCommand._.extend.name [as func] (/tools/cli/c
ommands.js:791:12)
           at /tools/cli/main.js:1378:23
       Installing meteor bundle
/tmp/buildpacks/bluemix-buildpack-meteor/bin/compile: line 127: cd: /tmp/staged/
app/.meteor/meteor_build/app/bundle/programs/server: No such file or directory
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed

**Comment by ZuSe** [comment]
I have the same problem with rocket chat.

Did you find any fix?
